### ISSUE TITLE
Run As Cucumber Feature fails silently

### ISSUE THREAD

**Issue by lancerkind** [cucumber/cucumber-eclipse#190]
I clean installed Ecilpse Neon and Spring Tool Suite on OS X and Windows 10, installed "Natural" plug in and cucumber-eclipse via Eclipse Install New Software and got the same results.  Java environment is Java 8.

What I did is:
Create a feature file.
Right click and choose Run As Cucumber Feature.

Resulted in:
no change in the interface,
no output to any of the consoles

As a workaround I:
install the cucumber jars to a directory, add them to my class path, create a JUnit test runner configured to run with Cucumber, and then I get correct behavior.

Another thing I tried:
Created a different run configuration for Cucumber and set the class path to the Cucumber libraries.  This got something executing and hence showed output to the console.  I may troubleshoot this further at a later date:
```
Exception in thread "main" cucumber.runtime.CucumberException: java.lang.NullPointerException
	at cucumber.runtime.java.JavaBackend.addStepDefinition(JavaBackend.java:156)
	at cucumber.runtime.java.MethodScanner.scan(MethodScanner.java:68)
	at cucumber.runtime.java.MethodScanner.scan(MethodScanner.java:41)
	at cucumber.runtime.java.JavaBackend.loadGlue(JavaBackend.java:86)
	at cucumber.runtime.Runtime.<init>(Runtime.java:92)
	at cucumber.runtime.Runtime.<init>(Runtime.java:70)
	at cucumber.runtime.Runtime.<init>(Runtime.java:66)
	at cucumber.api.cli.Main.run(Main.java:35)
	at cucumber.api.cli.Main.main(Main.java:18)
Caused by: java.lang.NullPointerException
	at cucumber.runtime.Utils.targetMethod(Utils.java:59)
	at cucumber.runtime.Utils.invoke(Utils.java:33)
	at cucumber.runtime.java.JavaBackend.pattern(JavaBackend.java:202)
	at cucumber.runtime.java.JavaBackend.addStepDefinition(JavaBackend.java:151)
```

Impacts: 
Although using JUnit to run tests is the best longterm approach, those new to Cucumber are going to assume the tool is broke or waste time as I did in trying to get it working instead of moving on to using JUnit to run tests.  Also, Run As Cucumber Feature is a convenient way to execute a single feature file rather than fiddle with JUnit tests which usually are configured to run all the files.

**Comment by andreas-wolf** [comment]
I have the same NPE. No idea what is wrong. In my case it came from 

```
package cucumber.runtime;

private static Method targetMethod(final Object target, final Method method) throws NoSuchMethodException {
        final Class<?> targetClass = target.getClass();
        final Class<?> declaringClass = method.getDeclaringClass();

        // Immediately return the provided method if the class loaders are the same.
        if (targetClass.getClassLoader().equals(declaringClass.getClassLoader())) {
            return method;
        } else {
```

targetClass.getClassLoader() returned null.

Probably that has to do with the fact that I had to add lots of jars to the runtime configuration classpath bootstrap entries. For some reason the maven dependencys where ignored completely.

**Comment by laeubi** [comment]
The main problem is, that the "core" cucumber that is used for this plugin is rather outdated. We need to rethink the whole concept of running from within eclipse feature files, so I mark this as well as bug and enhancement.

**Comment by laeubi** [comment]
The runner was improved in the 2.x line
