### ISSUE TITLE
Eclipse doesn't found jar files while installing this package offline

### ISSUE THREAD

**Issue by nizamuddinj** [cucumber/cucumber-eclipse#219]
I tried to install this package on Eclipse offline but got error an error that Eclipse doesn't found jar files. Is this known issue or is there any other way to install this package.

**Comment by girijant** [comment]
@nizamuddinj, 
Please share your detail steps for better investigation about this issue. Also attach issue snapshots and logs for better understanding. 

Thanks, 
Girija

**Comment by nizamuddinj** [comment]
Hi @girijant ,
I received the errors as below. I cannot access outside world and so cannot use Market place at my work place. So, I need to import plugins offline and I found the similar content i.e. same structured reposition on this git repository. Also not able to attached document in this window.
====================================================
eclipse.buildId=4.6.0.I20160606-1100
java.version=1.8.0_152
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

This is a continuation of log file C:\Users\njagirda\Documents\workspace\.metadata\.bak_0.log
Created Time: 2017-11-06 11:48:20.874
===============================================================
Below is the log error for this issue:
!ENTRY org.eclipse.equinox.p2.core 4 0 2017-11-03 15:13:14.942
!MESSAGE Provisioning exception
!STACK 1
org.eclipse.equinox.p2.core.ProvisionException: No repository found at jar:file:/C:/Users/njagirda/Documents/Selenium/cucumber-eclipse-master.zip/.
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.fail(AbstractRepositoryManager.java:395)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.oomph.util.ReflectUtil.invokeMethod(ReflectUtil.java:116)
	at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.fail(CachingRepositoryManager.java:314)
	at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.loadRepository(CachingRepositoryManager.java:217)
	at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager$Metadata.loadRepository(CachingRepositoryManager.java:437)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:96)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:92)
	at org.eclipse.equinox.p2.ui.LoadMetadataRepositoryJob.doLoad(LoadMetadataRepositoryJob.java:117)
	at org.eclipse.equinox.p2.ui.LoadMetadataRepositoryJob.runModal(LoadMetadataRepositoryJob.java:102)
	at org.eclipse.equinox.internal.p2.ui.sdk.PreloadingRepositoryHandler$2.runModal(PreloadingRepositoryHandler.java:83)
	at org.eclipse.equinox.p2.operations.ProvisioningJob.run(ProvisioningJob.java:177)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
!SUBENTRY 1 org.eclipse.equinox.p2.metadata.repository 4 1000 2017-11-03 15:13:14.943
!MESSAGE No repository found at jar:file:/C:/Users/njagirda/Documents/Selenium/cucumber-eclipse-master.zip/.
=============================================================
Hope this is helpful to investigate.
Please let me know once you have solution.
Regards,
Nizam

**Comment by girijant** [comment]
@nizamuddinj,
I would not recommend for offline-installation as the way what you are doing. Currently I am working to publish our cucumber-eclipse plugin for offline-installation. You will be notified once it's completed. Also I'm updating ticket as duplicate as ticket #209 is already exists.

Thanks,
-Girija

**Comment by girijant** [comment]
@nizamuddinj,
Glad to publish Cucumber-Eclipse plugin as a Zip file which can be downloaded and installed from your local system.

Please download the plugin-zip(cucumber-eclipse-plugin-0.0.19-SNAPSHOT.zip) from the latest version(0.0.19-SNAPSHOT) directory of below url:
- https://github.com/cucumber/cucumber-eclipse/tree/master/cucumber.eclipse.download/download

Also refer our [Plugin-Download/Installation-Wiki](https://github.com/cucumber/cucumber-eclipse/wiki/Download-and-Install-Plugin-From-Zip) for detail information

Hence closing this ticket.
