### ISSUE TITLE
Editor should be able to parse step definitions Before() (java8 syntax)

### ISSUE THREAD

**Issue by smrowley** [cucumber/cucumber-eclipse#234]
The java.util.regex.PatternSyntaxException is encountered when attempting to open a feature file with the plugin editor. The issue arises when a Before or After step is defined with a HookNoArgsBody.

Example:

`Before(() -> {
    //do something before
});`

Full stack trace:
`
at java.util.regex.Pattern.error(Unknown Source)
	at java.util.regex.Pattern.closure(Unknown Source)
	at java.util.regex.Pattern.sequence(Unknown Source)
	at java.util.regex.Pattern.expr(Unknown Source)
	at java.util.regex.Pattern.group0(Unknown Source)
	at java.util.regex.Pattern.sequence(Unknown Source)
	at java.util.regex.Pattern.expr(Unknown Source)
	at java.util.regex.Pattern.compile(Unknown Source)
	at java.util.regex.Pattern.<init>(Unknown Source)
	at java.util.regex.Pattern.compile(Unknown Source)
	at cucumber.eclipse.steps.integration.Step.setText(Step.java:27)
	at cucumber.eclipse.steps.jdt.StepDefinitions.getCukeSteps(StepDefinitions.java:194)
	at cucumber.eclipse.editor.steps.jdt.JDTStepDefinitions.collectCukeStepsFromSource(JDTStepDefinitions.java:109)
	at cucumber.eclipse.editor.steps.jdt.JDTStepDefinitions.getSteps(JDTStepDefinitions.java:74)
	at cucumber.eclipse.editor.steps.ExtensionRegistryStepProvider.reloadSteps(ExtensionRegistryStepProvider.java:43)
	at cucumber.eclipse.editor.steps.ExtensionRegistryStepProvider.<init>(ExtensionRegistryStepProvider.java:26)
	at cucumber.eclipse.editor.editors.Editor.doSetInput(Editor.java:177)
	at org.eclipse.ui.texteditor.AbstractTextEditor$5.run(AbstractTextEditor.java:3154)
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:437)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:353)
	at org.eclipse.ui.internal.WorkbenchWindow$14.run(WorkbenchWindow.java:2195)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.WorkbenchWindow.run(WorkbenchWindow.java:2191)
	at org.eclipse.ui.texteditor.AbstractTextEditor.internalInit(AbstractTextEditor.java:3172)
`

**Comment by Flaburgan** [comment]
I also have this, it looks like the regex is not able to handle the `Before()` lambda (Java8 syntax).
If the before instruction is set with the annotation `@Before` in a separated method, everything works as expected and the feature files can be open with the editor.

**Comment by girijant** [comment]
Thanks for sharing the issue. I will look into it very shortly.

**Comment by girijant** [comment]
Guys, 
Thanks for sharing issues.Waiting for any other issues in java8 - lambda expression, so that I could fix all in a single release build.

**Comment by girijant** [comment]
@Flaburgan, @smrowley,
Issue got fixed in 0.0.21-SNAPSHOT, Please retry by updating your existing plugin. So closing this ticket.

**Comment by Flaburgan** [comment]
It works now, thank you very much.
