### ISSUE TITLE
Step does not have a matching glue code

### ISSUE THREAD

**Issue by ag001** [cucumber/cucumber-eclipse#251]
I am using Eclipse Neon 2.0 and Cucumber (Cucumber Eclipse Feature) plugin version is 0.0.21.201802160922

All of the steps display a warning "Step <step name> does not have a matching glue code"
I am not able to step into the step definitions due to this issue. 

How to solve this? Thank you.

**Comment by Flaburgan** [comment]
Can you try to close and reopen the feature file, to reload the checker. If warnings are still there, please post the content of the feature file here.

**Comment by ag001** [comment]
@Flaburgan Thanks for your response. I have closed and reopened the feature file and opened other feature files, without any luck. Here is one of the feature files. 

Feature: AddMailingAddress

@UDFID0087538 @DSTSFOII_901_10_1 @coffee
Scenario: DSTSFOII_901_10_1-Add Permanent Mailing Address: Verify that clicking the add button will display a section to add mailing address.
	Given I login to "cxo" as a cpo basic user
	And I navigate to the About Me page
	And I navigate to the Mailing Address page via myprofilecomponent
	And I click on addMailingAddress
	And I click on addPermanentMailingAddress
	And I enter "AddressLine1" in mailingAddressLineOne
	And I enter "AddressLine2" in mailingAddressLineTwo
	And I enter "AddressLine3" in mailingAddressLineThree
	And I enter "AddressCity1" in mailingAddressCity
	And I click on stateId
	And I click on stateIdList with value "StateName1"
	And I enter "ZipCode1" in zipCode
	And I enter "ZipCodeExtension1" in zipCodeExtension
	And I check the makeThisAddressPrimary checkbox
	And I verify that saveMailingAddressChanges is enabled

**Comment by ag001** [comment]
Here is the warning: 

Description	Resource	Path	Location	Type
Step 'I click on addMailingAddress' does not have a matching glue code	AddMailingAddress.feature	/cxo/src/test/resources/features/ProfileAndServicing/PersonalDetails_MailingAddress	line 8	Unmatched step

**Comment by ag001** [comment]
I noticed this in the error log everytime I press F3 (Find step):
**Unhandled event loop exception**

org.eclipse.e4.core.di.InjectionException: java.lang.NullPointerException
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:65)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:282)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:264)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:488)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:433)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:454)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem$3.handleEvent(AbstractContributionItem.java:482)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4418)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4236)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3824)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
Caused by: java.lang.NullPointerException
	at cucumber.eclipse.editor.editors.PopupMenuFindStepHandler.openEditor(PopupMenuFindStepHandler.java:70)
	at cucumber.eclipse.editor.editors.PopupMenuFindStepHandler.execute(PopupMenuFindStepHandler.java:54)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:295)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
	at sun.reflect.GeneratedMethodAccessor72.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	... 37 more

**Session data:**
eclipse.buildId=4.6.2.M20161124-1400
java.version=1.8.0_144
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -data file:/C:/FAST/eclipse/workspaces/default/ -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product

**Comment by Flaburgan** [comment]
So is this step the only one not found? Is it defined in the same steps definition file than the others?

**Comment by ag001** [comment]
None of the steps are matching. They are in different project which I have imported and have set the cucumber user settings to point to the respective package name.

**Comment by girijant** [comment]
@ag001,
First build your project having step-definitions, add this project into your pom.xml of your current project as a dependency.Close all feature files from eclipse editor. Add root package name(s) in  cucumber user-settings preference page. Open feature file. If you use ctrl+space in your feature file, all steps in the jar/dependency can be populated.

Thanks,
GIRIJA

**Comment by girijant** [comment]
Closing this ticket.

**Comment by appusenthu21** [comment]
dgfd
