### ISSUE TITLE
NPE in SameLocationFilter with current Snapshot

### ISSUE THREAD

**Issue by laeubi** [cucumber/cucumber-eclipse#344]
java.lang.NullPointerException
	at cucumber.eclipse.steps.integration.filter.SameLocationFilter.accept(SameLocationFilter.java:16)
	at cucumber.eclipse.steps.integration.filter.SameLocationFilter.accept(SameLocationFilter.java:1)
	at cucumber.eclipse.steps.integration.filter.FilterUtil.filter(FilterUtil.java:9)
	at cucumber.eclipse.editor.builder.CucumberGherkinBuilder$MarkerFormatter.filter(CucumberGherkinBuilder.java:464)
	at cucumber.eclipse.editor.builder.CucumberGherkinBuilder$MarkerFormatter.validate(CucumberGherkinBuilder.java:399)
	at cucumber.eclipse.editor.builder.CucumberGherkinBuilder$MarkerFormatter.step(CucumberGherkinBuilder.java:498)
	at gherkin.formatter.model.Step.replay(Step.java:68)
	at gherkin.formatter.model.Step$Builder.replay(Step.java:41)
	at gherkin.parser.FormatterListener.replayStepsOrExamples(FormatterListener.java:151)
	at gherkin.parser.FormatterListener.scenarioOutline(FormatterListener.java:106)
	at gherkin.parser.Parser.scenarioOutline(Parser.java:118)
	at gherkin.lexer.De.scan(De.java:779)
	at gherkin.lexer.I18nLexer.scan(I18nLexer.java:36)
	at gherkin.parser.Parser.parse(Parser.java:62)
	at cucumber.eclipse.editor.builder.CucumberGherkinBuilder$CucumberGherkinBuildVisitor.buildGherkin(CucumberGherkinBuilder.java:277)
	at cucumber.eclipse.editor.builder.CucumberGherkinBuilder$CucumberGherkinBuildVisitor.visit(CucumberGherkinBuilder.java:217)
	at org.eclipse.core.internal.resources.Resource.lambda$1(Resource.java:117)
	at org.eclipse.core.internal.resources.Resource.lambda$0(Resource.java:85)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:85)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.iterate(ElementTreeIterator.java:135)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:94)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:55)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:117)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:105)
	at cucumber.eclipse.editor.builder.CucumberGherkinBuilder.fullBuild(CucumberGherkinBuilder.java:130)
	at cucumber.eclipse.editor.builder.CucumberGherkinBuilder.build(CucumberGherkinBuilder.java:92)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:833)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:278)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:468)
	at org.eclipse.core.internal.resources.Project$1.run(Project.java:574)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2295)
	at org.eclipse.core.internal.resources.Project.internalBuild(Project.java:548)
	at org.eclipse.core.internal.resources.Project.build(Project.java:116)
	at cucumber.eclipse.steps.integration.builder.BuilderUtil$2.runInWorkspace(BuilderUtil.java:43)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by laeubi** [comment]
If a step is derived not from the current project but from a referenced clasppath-entry there might be no source avaiable. In this case getResource() might return null what seems to be the issue here.

**Comment by laeubi** [comment]
Another possible problem might be that the resource is there, but the parent is null, so this should be checked also

**Comment by SuperOok** [comment]
> If a step is derived not from the current project but from a referenced clasppath-entry there might be no source avaiable. In this case getResource() might return null what seems to be the issue here.

What if the source is available but in another project in the workspace? Will it be found?

**Comment by laeubi** [comment]
If the project is added as a referenced project: yes.

This was fixed and is available in the snapshot now.
