### ISSUE TITLE
CucumberGherkinBuilder throws Exception

### ISSUE THREAD

**Issue by laeubi** [cucumber/cucumber-eclipse#349]
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at cucumber.eclipse.editor.builder.CucumberGherkinBuilder$MarkerFormatter.getExampleVariablesMap(CucumberGherkinBuilder.java:472)
        at cucumber.eclipse.editor.builder.CucumberGherkinBuilder$MarkerFormatter.matchScenarioOutlineExample(CucumberGherkinBuilder.java:368)
        at cucumber.eclipse.editor.builder.CucumberGherkinBuilder$MarkerFormatter.examples(CucumberGherkinBuilder.java:359)
        at gherkin.formatter.model.Examples.replay(Examples.java:56)
        at gherkin.formatter.model.Examples$Builder.replay(Examples.java:41)
        at gherkin.parser.FormatterListener.replayStepsOrExamples(FormatterListener.java:151)
        at gherkin.parser.FormatterListener.eof(FormatterListener.java:138)
        at gherkin.parser.Parser.eof(Parser.java:153)
        at gherkin.lexer.De.scan(De.java:914)
        at gherkin.lexer.I18nLexer.scan(I18nLexer.java:36)
        at gherkin.parser.Parser.parse(Parser.java:62)
        at cucumber.eclipse.editor.builder.CucumberGherkinBuilder$CucumberGherkinBuildVisitor.buildGherkin(CucumberGherkinBuilder.java:277)
        at cucumber.eclipse.editor.builder.CucumberGherkinBuilder$CucumberGherkinBuildVisitor.visit(CucumberGherkinBuilder.java:217)
        at org.eclipse.core.internal.resources.Resource$2.visit(Resource.java:120)
        at org.eclipse.core.internal.resources.Resource$1.visitElement(Resource.java:84)
        at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:82)
        at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
        at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
        at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
        at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
        at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
        at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
        at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
        at org.eclipse.core.internal.watson.ElementTreeIterator.iterate(ElementTreeIterator.java:129)
        at org.eclipse.core.internal.resources.Resource.accept(Resource.java:94)
        at org.eclipse.core.internal.resources.Resource.accept(Resource.java:52)
        at org.eclipse.core.internal.resources.Resource.accept(Resource.java:117)
        at org.eclipse.core.internal.resources.Resource.accept(Resource.java:105)
        at cucumber.eclipse.editor.builder.CucumberGherkinBuilder.fullBuild(CucumberGherkinBuilder.java:130)
        at cucumber.eclipse.editor.builder.CucumberGherkinBuilder.build(CucumberGherkinBuilder.java:92)
        at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
        at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
        at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
        at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
        at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
        at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

**Comment by laeubi** [comment]
@SuperOok This seems to happen when the examples table is misaligned (e.g. the number of cols does not match the number of variables like in


```
  Examples:
    | day | answer |
    | "Friday" |
    | "Sunday" | "Nope" |
    | "anything else!" | "Nope" |
```

**Comment by laeubi** [comment]
![grafik](https://user-images.githubusercontent.com/1331477/55858648-89549f80-5b70-11e9-8864-9b9983dee2c4.png)
A new error marker is now shown to inform the user about the issue
