### ISSUE TITLE
java.lang.ClassNotFoundException: org.springframework.core.annotation.MergedAnnotations$SearchStrategy while triggering tests

### ISSUE THREAD

**Issue by Shebeok** [cucumber/cucumber-eclipse#381]
When I am trying to run the feature file with cucumber file facing the below issue and same runs fine via maven. I am using cucumber version 4.8.0.

Dec 05, 2019 5:46:32 AM cucumber.api.cli.Main run
WARNING: You are using deprecated Main class. Please use io.cucumber.core.cli.Main
Dec 05, 2019 5:46:33 AM cucumber.runtime.java.ObjectFactoryLoader loadSingleObjectFactory
INFO: Loading ObjectFactory via service loader: io.cucumber.spring.SpringFactory
Dec 05, 2019 5:46:35 AM cucumber.runtime.Runtime run
SEVERE: Exception while executing pickle
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: org/springframework/core/annotation/MergedAnnotations$SearchStrategy
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at cucumber.runtime.Runtime.run(Runtime.java:114)
	at io.cucumber.core.cli.Main.run(Main.java:43)
	at cucumber.api.cli.Main.run(Main.java:28)
	at cucumber.api.cli.Main.main(Main.java:15)
Caused by: java.lang.NoClassDefFoundError: org/springframework/core/annotation/MergedAnnotations$SearchStrategy
	at org.springframework.boot.test.context.ImportsContextCustomizerFactory.createContextCustomizer(ImportsContextCustomizerFactory.java:44)
	at org.springframework.test.context.support.AbstractTestContextBootstrapper.getContextCustomizers(AbstractTestContextBootstrapper.java:404)
	at org.springframework.test.context.support.AbstractTestContextBootstrapper.buildMergedContextConfiguration(AbstractTestContextBootstrapper.java:376)
	at org.springframework.test.context.support.AbstractTestContextBootstrapper.buildMergedContextConfiguration(AbstractTestContextBootstrapper.java:294)
	at org.springframework.test.context.support.AbstractTestContextBootstrapper.buildTestContext(AbstractTestContextBootstrapper.java:108)
	at org.springframework.test.context.TestContextManager.<init>(TestContextManager.java:137)
	at io.cucumber.spring.SpringFactory$CucumberTestContextManager.<init>(SpringFactory.java:238)
	at io.cucumber.spring.SpringFactory.start(SpringFactory.java:133)
	at cucumber.runtime.java.ObjectFactoryLoader$ObjectFactoryAdapter.start(ObjectFactoryLoader.java:142)
	at cucumber.runtime.java.JavaBackend.buildWorld(JavaBackend.java:143)
	at cucumber.runner.Runner.buildBackendWorlds(Runner.java:130)
	at cucumber.runner.Runner.runPickle(Runner.java:48)
	at cucumber.runtime.Runtime$1.run(Runtime.java:104)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at cucumber.runtime.Runtime$SameThreadExecutorService.execute(Runtime.java:258)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at cucumber.runtime.Runtime.run(Runtime.java:101)
	... 3 more
Caused by: java.lang.ClassNotFoundException: org.springframework.core.annotation.MergedAnnotations$SearchStrategy
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 21 more

Exception in thread "main" cucumber.runtime.CucumberException: java.lang.NoClassDefFoundError: org/springframework/core/annotation/MergedAnnotations$SearchStrategy
	at cucumber.runtime.Runtime.run(Runtime.java:124)
	at io.cucumber.core.cli.Main.run(Main.java:43)
	at cucumber.api.cli.Main.run(Main.java:28)
	at cucumber.api.cli.Main.main(Main.java:15)
Caused by: java.lang.NoClassDefFoundError: org/springframework/core/annotation/MergedAnnotations$SearchStrategy
	at org.springframework.boot.test.context.ImportsContextCustomizerFactory.createContextCustomizer(ImportsContextCustomizerFactory.java:44)
	at org.springframework.test.context.support.AbstractTestContextBootstrapper.getContextCustomizers(AbstractTestContextBootstrapper.java:404)
	at org.springframework.test.context.support.AbstractTestContextBootstrapper.buildMergedContextConfiguration(AbstractTestContextBootstrapper.java:376)
	at org.springframework.test.context.support.AbstractTestContextBootstrapper.buildMergedContextConfiguration(AbstractTestContextBootstrapper.java:294)
	at org.springframework.test.context.support.AbstractTestContextBootstrapper.buildTestContext(AbstractTestContextBootstrapper.java:108)
	at org.springframework.test.context.TestContextManager.<init>(TestContextManager.java:137)
	at io.cucumber.spring.SpringFactory$CucumberTestContextManager.<init>(SpringFactory.java:238)
	at io.cucumber.spring.SpringFactory.start(SpringFactory.java:133)
	at cucumber.runtime.java.ObjectFactoryLoader$ObjectFactoryAdapter.start(ObjectFactoryLoader.java:142)
	at cucumber.runtime.java.JavaBackend.buildWorld(JavaBackend.java:143)
	at cucumber.runner.Runner.buildBackendWorlds(Runner.java:130)
	at cucumber.runner.Runner.runPickle(Runner.java:48)
	at cucumber.runtime.Runtime$1.run(Runtime.java:104)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at cucumber.runtime.Runtime$SameThreadExecutorService.execute(Runtime.java:258)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at cucumber.runtime.Runtime.run(Runtime.java:101)
	... 3 more
Caused by: java.lang.ClassNotFoundException: org.springframework.core.annotation.MergedAnnotations$SearchStrategy
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 21 more

**Comment by qvdk** [comment]
Hello
Could you provide a sample to reproduce this issue please ?

**Comment by badigeranand007** [comment]
I am facing the same issue. I have upgraded Springboot 2.2.4 and I started gettin gmy Junits failing
INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running ManifestUtilsTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.017 s <<< FAILURE! - in ManifestUtilsTest
[ERROR] initializationError  Time elapsed: 0.013 s  <<< ERROR!
java.lang.NoClassDefFoundError: org/springframework/core/annotation/MergedAnnotations$SearchStrategy

[INFO] Running DocUtilsTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 s <<< FAILURE! - in DocUtilsTest
[ERROR] initializationError  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: org/springframework/core/annotation/MergedAnnotations$SearchStrategy

[INFO] Running DocConfigControllerTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 s <<< FAILURE! - in DocConfigControllerTest
[ERROR] initializationError  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: org/springframework/core/annotation/MergedAnnotations$SearchStrategy

[INFO] Running AppControllerTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 s <<< FAILURE! - in AppControllerTest
[ERROR] initializationError  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: org/springframework/core/annotation/MergedAnnotations$SearchStrategy

[INFO] Running ManifestControllerTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 s <<< FAILURE! - in ManifestControllerTest
[ERROR] initializationError  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: org/springframework/core/annotation/MergedAnnotations$SearchStrategy

[INFO] Running ManifestServiceTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 s <<< FAILURE! - in ManifestServiceTest
[ERROR] initializationError  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: org/springframework/core/annotation/MergedAnnotations$SearchStrategy

**Comment by badigeranand007** [comment]
Please help here is the my parent and child pom.xml


Parent.pom
![image](https://user-images.githubusercontent.com/60767277/73999938-5320b180-4934-11ea-9358-bdfa72cd71e9.png)
CHild.pom
![image](https://user-images.githubusercontent.com/60767277/73999962-65025480-4934-11ea-8149-52384cb858fb.png)

**Comment by manalilrafeeq** [comment]
just try  <spring-cloud.version>Hoxton.SR1</spring-cloud.version>

<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-parent</artifactId>
	<version>${spring-cloud.version}</version>							</dependency>

**Comment by manalilrafeeq** [comment]
@badigeranand007  @Shebeok 

just try with <spring-cloud.version>Hoxton.SR1</spring-cloud.version> in your pom.xml file like below :

``

<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-parent</artifactId>
	<version>${spring-cloud.version}</version>
</dependency>

**Comment by laeubi** [comment]
No feedback until now, please reopen with further details if this is still relevant for you.
