### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by Safi101** [cucumber/cucumber-eclipse#409]
Hello,
Environment: Eclipse, cucumber and maven.

When I run as jUnit and I get the below error. Please advise.

**Feature:**
`Feature: Free_CRM_LOGIN_FEATURE
Scenario: Free crm login scenario

Given User is already on login page
When title is crom
Then user enters user name and password
Then User clicks login button
And User is on home page
`

Runner:
```
package MyRunner;

import org.junit.runner.RunWith;

import io.cucumber.junit.Cucumber;
import io.cucumber.junit.CucumberOptions;
//import cucumber.junit.Cucumber; 

//import cucumber.api.CucumberOptions;
//import cucumber.api.junit.Cucumber;


@RunWith(Cucumber.class)
@CucumberOptions(
		features = "C:/Cucumber2/src/main/java/Features/log_in.feature",
		glue="src/main/java/stepDefinition",
		//format = {"pretty", "html:target/Destination"} 
		plugin = {"pretty","html:test-outout"}
      )
public class TestRunner {

}
```
Error:

```
Class not found MyRunner.TestRunner
java.lang.ClassNotFoundException: MyRunner.TestRunner
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.loadClass(RemoteTestRunner.java:688)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.loadClasses(RemoteTestRunner.java:421)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:444)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

```
![d1](https://user-images.githubusercontent.com/23562588/82739596-aa456900-9d0e-11ea-8a6f-86c5c0c1e4cf.png)

**Comment by laeubi** [comment]
This happens if there are build path problems please check your project setup or provide a reporducer.

**Comment by Rkharat2312** [comment]
@softwaredev999 how you resolve this issue?
I am getting same issue

**Comment by 786hai** [comment]
I am also having same issue
Class not found cucumberOptions.JunitTestRunnerTest
java.lang.ClassNotFoundException: cucumberOptions.JunitTestRunnerTest
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.loadClass(RemoteTestRunner.java:768)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.loadClasses(RemoteTestRunner.java:491)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:514)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:758)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:453)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:211)
![image](https://github.com/user-attachments/assets/e33c9d61-b2e5-4e7e-9c7a-6caf864726ce)
